if !has('gui_running') && str2nr(&t_Co) < 256
  set t_Co=256
endif

syntax on

set mouse=a

let s:khzhao_vim_home = empty($KHZHAO_HOME) ? expand('~/.khzhao/vim') : $KHZHAO_HOME . '/vim'
execute 'set runtimepath^=' . fnameescape(s:khzhao_vim_home)
let s:khzhao_vim_after = fnamemodify(resolve(expand('<sfile>:p')), ':h:h') . '/vim/after'
if isdirectory(s:khzhao_vim_after)
  execute 'set runtimepath+=' . fnameescape(s:khzhao_vim_after)
endif

call plug#begin(s:khzhao_vim_home . '/plugged')
Plug 'preservim/nerdtree'
Plug 'ap/vim-buftabline'
Plug 'morhetz/gruvbox'
call plug#end()

" NERDTree file explorer.
let g:NERDTreeWinPos = 'left'
let g:NERDTreeWinSize = 30
let g:NERDTreeQuitOnOpen = 0
let g:NERDTreeChDirMode = 0
let g:khzhao_nerdtree_root = getcwd()
let s:khzhao_next_tab_id = 1
let s:khzhao_closing_tab_buffers = []
let s:khzhao_tabclose_bang = 0

function! s:IsGitEditorBuffer() abort
  let l:name = expand('%:t')
  let l:path = expand('%:p')

  if &filetype ==# 'gitcommit' || &filetype ==# 'gitrebase'
    return 1
  endif

  if l:name =~# '\v^(COMMIT_EDITMSG|MERGE_MSG|TAG_EDITMSG|SQUASH_MSG|git-rebase-todo)(\.backup)?$'
    return 1
  endif

  return l:path =~# '\v/\.git/(rebase-merge|rebase-apply)/'
endfunction

function! s:ListedFileBuffers() abort
  return filter(<SID>ScopedUserBuffers(), '!empty(bufname(v:val)) || getbufvar(v:val, "&modified")')
endfunction

function! s:EnsureTabState() abort
  if !exists('t:khzhao_tab_id')
    let t:khzhao_tab_id = s:khzhao_next_tab_id
    let s:khzhao_next_tab_id += 1
  endif
endfunction

function! s:IsUserBuffer(bufnr) abort
  return buflisted(a:bufnr)
        \ && getbufvar(a:bufnr, '&buftype') ==# ''
        \ && getbufvar(a:bufnr, '&filetype') !=# 'nerdtree'
endfunction

function! s:RememberBufferOwner(bufnr) abort
  if !<SID>IsUserBuffer(a:bufnr)
    return
  endif

  call <SID>EnsureTabState()
  if getbufvar(a:bufnr, 'khzhao_owner_tab_id', 0) == 0
    call setbufvar(a:bufnr, 'khzhao_owner_tab_id', t:khzhao_tab_id)
  endif
endfunction

function! s:RememberCurrentTabBuffers() abort
  call <SID>EnsureTabState()
  for l:buf in tabpagebuflist()
    call <SID>RememberBufferOwner(l:buf)
  endfor
endfunction

function! s:ScopedUserBuffers() abort
  call <SID>RememberCurrentTabBuffers()
  let l:buffers = []
  let l:tab_id = t:khzhao_tab_id

  for l:buf in range(1, bufnr('$'))
    if <SID>IsUserBuffer(l:buf) && getbufvar(l:buf, 'khzhao_owner_tab_id', 0) == l:tab_id
      call add(l:buffers, l:buf)
    endif
  endfor

  return l:buffers
endfunction

function! KhzhaoScopedUserBuffers() abort
  return <SID>ScopedUserBuffers()
endfunction

function! s:CaptureClosingTabBuffers() abort
  call <SID>RememberCurrentTabBuffers()
  let s:khzhao_closing_tab_buffers = []

  for l:buf in range(1, bufnr('$'))
    if <SID>IsUserBuffer(l:buf) && getbufvar(l:buf, 'khzhao_owner_tab_id', 0) == t:khzhao_tab_id
      call add(s:khzhao_closing_tab_buffers, l:buf)
    endif
  endfor
endfunction

function! s:DeleteClosedTabBuffers() abort
  let l:visible_buffers = []
  for l:tab in range(1, tabpagenr('$'))
    call extend(l:visible_buffers, tabpagebuflist(l:tab))
  endfor

  for l:buf in s:khzhao_closing_tab_buffers
    if buflisted(l:buf) && index(l:visible_buffers, l:buf) < 0
      silent! execute 'bdelete' . (s:khzhao_tabclose_bang ? '!' : '') . ' ' . l:buf
    endif
  endfor

  let s:khzhao_closing_tab_buffers = []
  let s:khzhao_tabclose_bang = 0
  if exists('*buftabline#update')
    call buftabline#update(0)
  endif
endfunction

function! s:OpenNERDTree() abort
  if !exists(':NERDTree') || <SID>IsGitEditorBuffer()
    return
  endif

  let l:current_win = win_getid()
  silent! execute 'NERDTree' fnameescape(g:khzhao_nerdtree_root)
  call win_gotoid(l:current_win)
endfunction

function! s:FocusNERDTree() abort
  call <SID>OpenNERDTree()
  if exists(':NERDTreeFocus')
    NERDTreeFocus
  endif
endfunction

function! s:SwitchToBuffer(bufnr) abort
  let l:return_win = 0
  if &filetype ==# 'nerdtree'
    let l:return_win = win_getid()
    wincmd l
    if &filetype ==# 'nerdtree'
      return
    endif
  endif

  execute 'buffer' a:bufnr
  if l:return_win
    call win_gotoid(l:return_win)
  endif
endfunction

function! s:ScopedNeighbor(bufnr, direction) abort
  let l:buffers = <SID>ScopedUserBuffers()
  if len(l:buffers) < 2
    return 0
  endif

  let l:idx = index(l:buffers, a:bufnr)
  if l:idx < 0
    return l:buffers[0]
  endif

  let l:step = a:direction ==# 'previous' ? -1 : 1
  return l:buffers[(l:idx + l:step + len(l:buffers)) % len(l:buffers)]
endfunction

function! s:DeleteFileBuffer(...) abort
  let l:bang = get(a:000, 0, 0)
  let l:return_win = 0
  if &filetype ==# 'nerdtree'
    let l:return_win = win_getid()
    wincmd l
    if &filetype ==# 'nerdtree'
      return
    endif
  endif

  let l:delete_buf = bufnr('%')
  let l:target_buf = <SID>ScopedNeighbor(l:delete_buf, 'previous')
  if &modified && !l:bang
    echohl WarningMsg
    echo 'Buffer has unsaved changes; write or discard before deleting'
    echohl None
    if l:return_win
      call win_gotoid(l:return_win)
    endif
    return
  endif

  if l:target_buf
    call <SID>SwitchToBuffer(l:target_buf)
  else
    enew
    call <SID>RememberBufferOwner(bufnr('%'))
  endif
  execute 'bdelete' . (l:bang ? '!' : '') . ' ' . l:delete_buf

  if l:return_win
    call win_gotoid(l:return_win)
  endif
endfunction

function! s:CloseCurrentTab(bang) abort
  let s:khzhao_tabclose_bang = a:bang
  try
    execute 'tabclose' . (a:bang ? '!' : '')
  finally
    let s:khzhao_tabclose_bang = 0
  endtry
endfunction

function! s:SmartQuit(bang) abort
  if tabpagenr('$') > 1
    call <SID>CloseCurrentTab(a:bang)
    return
  endif

  if <SID>IsGitEditorBuffer()
    execute 'quit' . (a:bang ? '!' : '')
    return
  endif

  if empty(<SID>ListedFileBuffers())
    execute 'quitall' . (a:bang ? '!' : '')
    return
  endif

  call <SID>DeleteFileBuffer(a:bang)
endfunction

function! s:SmartWriteQuit(bang) abort
  if &buftype ==# '' && &modified
    execute 'write' . (a:bang ? '!' : '')
  endif

  call <SID>SmartQuit(a:bang)
endfunction

function! s:CycleScopedFileBuffer(direction) abort
  let l:current_win = win_getid()
  if &filetype ==# 'nerdtree'
    wincmd l
    if win_getid() == l:current_win
      return
    endif
  endif

  let l:target = <SID>ScopedNeighbor(bufnr('%'), a:direction)
  if l:target
    call <SID>SwitchToBuffer(l:target)
  endif

  if win_id2win(l:current_win)
    call win_gotoid(l:current_win)
  endif
endfunction

function! s:PromptBufferSwitch() abort
  let l:buffers = <SID>ScopedUserBuffers()
  if empty(l:buffers)
    echo 'No buffers in this tab'
    return
  endif

  echo 'Buffers in this tab:'
  for l:buf in l:buffers
    let l:name = empty(bufname(l:buf)) ? '[No Name]' : fnamemodify(bufname(l:buf), ':~:.')
    echo printf('%3d %s', l:buf, l:name)
  endfor

  let l:buf = str2nr(input('Buffer: '))
  redraw
  if index(l:buffers, l:buf) < 0
    return
  endif

  call <SID>SwitchToBuffer(l:buf)
endfunction

function! s:SmartQuitCommandEnter() abort
  if getcmdtype() ==# ':' && getcmdline() =~# '^\s*q\%[uit]!\?\s*$'
    let l:bang = getcmdline() =~# '!\s*$'
    return "\<C-U>KhzhaoSmartQuit" . (l:bang ? '!' : '') . "\<CR>"
  endif

  if getcmdtype() ==# ':' && getcmdline() =~# '^\s*wq!\?\s*$'
    let l:bang = getcmdline() =~# '!\s*$'
    return "\<C-U>KhzhaoSmartWriteQuit" . (l:bang ? '!' : '') . "\<CR>"
  endif

  return "\<CR>"
endfunction

function! s:ShortenNERDTreeRoot() abort
  if &filetype !=# 'nerdtree' || !exists('b:NERDTree')
    return
  endif

  if get(b:, 'khzhao_shortening_nerdtree_root', 0)
    return
  endif

  let l:root_line = b:NERDTree.ui.getRootLineNum()
  if l:root_line < 1 || l:root_line > line('$')
    return
  endif

  let l:root_name = fnamemodify(b:NERDTree.root.path.str(), ':t')
  if empty(l:root_name)
    let l:root_name = fnamemodify(b:NERDTree.root.path.str(), ':h:t')
  endif

  if empty(l:root_name)
    let l:root_label = '/'
  else
    let l:root_label = '/' . l:root_name . '/'
  endif

  if getline(l:root_line) ==# l:root_label
    return
  endif

  let l:was_modifiable = &l:modifiable
  let l:was_readonly = &l:readonly
  let b:khzhao_shortening_nerdtree_root = 1

  try
    setlocal modifiable noreadonly
    call setline(l:root_line, l:root_label)
  finally
    if !l:was_modifiable
      setlocal nomodifiable
    endif
    if l:was_readonly
      setlocal readonly
    endif
    let b:khzhao_shortening_nerdtree_root = 0
  endtry
endfunction

function! s:NERDTreeUIRenderWrapper() dict abort
  call self.khzhao_original_render()
  call <SID>ShortenNERDTreeRoot()
endfunction

function! s:WrapNERDTreeRender() abort
  if &filetype !=# 'nerdtree' || !exists('b:NERDTree') || !has_key(b:NERDTree, 'ui')
    return
  endif

  if has_key(b:NERDTree.ui, 'khzhao_original_render')
    return
  endif

  let b:NERDTree.ui.khzhao_original_render = b:NERDTree.ui.render
  let b:NERDTree.ui.render = function('<SID>NERDTreeUIRenderWrapper', [], b:NERDTree.ui)
endfunction

function! s:PrepareNERDTree() abort
  call <SID>WrapNERDTreeRender()
  call <SID>ShortenNERDTreeRoot()
endfunction

function! s:NERDTreeKeymaps() abort
  setlocal nowrap
  call <SID>PrepareNERDTree()
  nnoremap <buffer> <C-j> 5j
  nnoremap <buffer> <C-k> 5k
  nnoremap <buffer> <C-h> 5h
  nnoremap <buffer> <C-l> 5l
  nnoremap <buffer> H :call <SID>CycleScopedFileBuffer('previous')<CR>
  nnoremap <buffer> L :call <SID>CycleScopedFileBuffer('next')<CR>
  nnoremap <buffer> <silent> q :KhzhaoSmartQuit<CR>
endfunction

command! -bang KhzhaoSmartQuit call <SID>SmartQuit(<bang>0)
command! -bang KhzhaoSmartWriteQuit call <SID>SmartWriteQuit(<bang>0)
command! KhzhaoBuffers call <SID>PromptBufferSwitch()
cnoremap <expr> <CR> <SID>SmartQuitCommandEnter()

augroup khzhao_buffers
  autocmd!
  autocmd BufAdd * call <SID>RememberBufferOwner(str2nr(expand('<abuf>')))
  autocmd TabClosedPre * call <SID>CaptureClosingTabBuffers()
  autocmd TabClosed * call <SID>DeleteClosedTabBuffers()
augroup END

augroup khzhao_nerdtree
  autocmd!
  autocmd VimEnter * call <SID>OpenNERDTree()
  autocmd FileType nerdtree call <SID>NERDTreeKeymaps()
  autocmd User NERDTreeInit call <SID>PrepareNERDTree()
  autocmd BufEnter,WinEnter * call <SID>PrepareNERDTree()
augroup END

nnoremap <leader>n :call <SID>FocusNERDTree()<CR>
nnoremap <leader>b :KhzhaoBuffers<CR>
nnoremap <leader>x :call <SID>DeleteFileBuffer()<CR>

set number
set linebreak
set textwidth=250
set visualbell

set hlsearch
set smartcase
set ignorecase

set shiftwidth=2
set smartindent
set smarttab
set softtabstop=2

set undolevels=9999
set backspace=indent,eol,start

inoremap { {}<Esc>ha
set whichwrap+=<,>,[,]

imap FF <Esc>

map <C-j> 5j
map <C-k> 5k
map <C-h> 5h
map <C-l> 5l

set expandtab
set pastetoggle=<C-p>

nnoremap <C-t> :tabnew<CR>
nnoremap H :call <SID>CycleScopedFileBuffer('previous')<CR>
nnoremap L :call <SID>CycleScopedFileBuffer('next')<CR>
vnoremap <C-r> "hy:%s/<C-r>h//gc<left><left><left>

function FormatBuffer()
  if &modified && !empty(findfile('.clang-format', expand('%:p:h') . ';'))
    let cursor_pos = getpos('.')
    :%!clang-format
    call setpos('.', cursor_pos)
  endif
endfunction

autocmd BufWritePre *.h,*.hpp,*.c,*.cpp,*.vert,*.frag :call FormatBuffer()
let g:gruvbox_termcolors = 256
set background=dark
try
  colorscheme gruvbox
catch /^Vim\%((\a\+)\)\=:E185/
  colorscheme desert
endtry
